name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

env:
  FLUTTER_VERSION: 3.16.3

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ env.FLUTTER_VERSION }}'
          cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "25.x"
      - name: Install Flutter Dependencies
        run: flutter pub get && flutter pub global activate protoc_plugin

      - name: Generate Code
        run: make all

      - name: Build Android Binary
        run: flutter build apk --target-platform android-arm,android-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-release.apk
